# Generated by Django 4.2.7 on 2026-03-27 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_ticket_assigned_to_alter_ticket_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('escalation_level', models.IntegerField(default=1, verbose_name='Escalation Level')),
                ('threshold_hours', models.IntegerField(default=48, help_text='Hours before this rule triggers.', verbose_name='Threshold (hours)')),
                ('target_role', models.CharField(blank=True, help_text='Optional: role/group name to escalate to.', max_length=255, null=True, verbose_name='Target Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Escalation Rule',
                'verbose_name_plural': 'Escalation Rules',
                'ordering': ['escalation_level'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_escalation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_escalation_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_owned', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(blank=True, help_text='The user this account escalates to after 48 hrs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to=settings.AUTH_USER_MODEL, verbose_name='Manager / escalation target')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_level', models.IntegerField(default=1, verbose_name='Escalation Level')),
                ('escalated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Escalated At')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20, verbose_name='Status')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification Sent')),
                ('escalated_from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Escalated From')),
                ('escalated_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_received', to=settings.AUTH_USER_MODEL, verbose_name='Escalated To')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='main.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Escalation',
                'verbose_name_plural': 'Ticket Escalations',
                'ordering': ['-escalated_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1_hours', models.IntegerField(default=48, help_text='Hours a ticket stays open before Level-1 escalation.', verbose_name='Level 1 threshold (hours)')),
                ('level2_hours', models.IntegerField(default=24, help_text='Hours after Level-1 before Level-2 escalation.', verbose_name='Level 2 threshold (hours)')),
                ('is_active', models.BooleanField(default=True)),
                ('top_level_user', models.ForeignKey(blank=True, help_text='All Level-2 escalations are assigned to this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_level_escalations', to=settings.AUTH_USER_MODEL, verbose_name='Top-level escalation user')),
            ],
            options={
                'verbose_name': 'Escalation Config',
                'verbose_name_plural': 'Escalation Config',
            },
        ),
    ]
