# Generated by Django 4.2.7 on 2026-03-27 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_escalationrule_ticket_escalation_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationconfig',
            name='level1_hours',
        ),
        migrations.RemoveField(
            model_name='escalationconfig',
            name='level2_hours',
        ),
        migrations.AddField(
            model_name='escalationconfig',
            name='level1_minutes',
            field=models.IntegerField(default=2880, help_text='Minutes a WAITING ticket is untouched before Level-1 escalation.', verbose_name='Level 1 threshold (minutes)'),
        ),
        migrations.AddField(
            model_name='escalationconfig',
            name='level2_minutes',
            field=models.IntegerField(default=1440, help_text='Minutes after Level-1 before Level-2 escalation.', verbose_name='Level 2 threshold (minutes)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The user this account escalates to after the L1 threshold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to=settings.AUTH_USER_MODEL, verbose_name='Manager / escalation target'),
        ),
    ]
