# Generated by Django 4.2.7 on 2026-03-27 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_escalationconfig_level1_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationconfig',
            name='top_level_user',
        ),
        migrations.AddField(
            model_name='escalationconfig',
            name='level1_target',
            field=models.ForeignKey(blank=True, help_text='User who receives Level 1 escalations (usually the manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_escalations', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Escalation Target'),
        ),
        migrations.AddField(
            model_name='escalationconfig',
            name='level2_target',
            field=models.ForeignKey(blank=True, help_text='User who receives Level 2 escalations (higher management)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level2_escalations', to=settings.AUTH_USER_MODEL, verbose_name='Level 2 Escalation Target'),
        ),
    ]
