# Generated by Django 4.2.7 on 2026-03-27 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_remove_escalationconfig_top_level_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='manager',
        ),
        migrations.AlterField(
            model_name='escalationconfig',
            name='level1_minutes',
            field=models.IntegerField(default=2880, help_text='Minutes before Level 1 escalation', verbose_name='Level 1 threshold (minutes)'),
        ),
        migrations.AlterField(
            model_name='escalationconfig',
            name='level1_target',
            field=models.ForeignKey(blank=True, help_text='Select who receives Level 1 escalations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_escalations', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Escalation Target'),
        ),
        migrations.AlterField(
            model_name='escalationconfig',
            name='level2_minutes',
            field=models.IntegerField(default=1440, help_text='Minutes before Level 2 escalation', verbose_name='Level 2 threshold (minutes)'),
        ),
        migrations.AlterField(
            model_name='escalationconfig',
            name='level2_target',
            field=models.ForeignKey(blank=True, help_text='Select who receives Level 2 escalations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level2_escalations', to=settings.AUTH_USER_MODEL, verbose_name='Level 2 Escalation Target'),
        ),
    ]
