# Generated by Django 4.2.7 on 2026-03-27 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_userprofile_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level1_target',
            field=models.ForeignKey(blank=True, help_text='Who this user escalates to at Level 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_escalations_received', to=settings.AUTH_USER_MODEL, verbose_name='Level 1 Escalation Target'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level2_target',
            field=models.ForeignKey(blank=True, help_text='Who this user escalates to at Level 2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level2_escalations_received', to=settings.AUTH_USER_MODEL, verbose_name='Level 2 Escalation Target'),
        ),
    ]
