# Generated by Django 4.2.7 on 2026-03-27 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile_level1_target_userprofile_level2_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketescalation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
