# Generated by Django 4.2.7 on 2026-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ticketescalation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationconfig',
            name='level1_target',
        ),
        migrations.RemoveField(
            model_name='escalationconfig',
            name='level2_target',
        ),
        migrations.AlterField(
            model_name='escalationconfig',
            name='level1_minutes',
            field=models.IntegerField(default=2880, help_text='Minutes a WAITING ticket is untouched before Level-1 escalation', verbose_name='Level 1 threshold (minutes)'),
        ),
        migrations.AlterField(
            model_name='escalationconfig',
            name='level2_minutes',
            field=models.IntegerField(default=1440, help_text='Minutes after Level-1 before Level-2 escalation', verbose_name='Level 2 threshold (minutes)'),
        ),
    ]
