# Generated by Django 4.2.7 on 2026-04-02 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_remove_escalationconfig_level1_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='level1_target',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level2_target',
        ),
        migrations.AddField(
            model_name='escalationconfig',
            name='level1_manager',
            field=models.ForeignKey(blank=True, help_text='All tickets escalate to this person at Level 1.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l1_escalations', to=settings.AUTH_USER_MODEL, verbose_name='Contact Center Manager (Level 1)'),
        ),
        migrations.AddField(
            model_name='escalationconfig',
            name='level2_director',
            field=models.ForeignKey(blank=True, help_text='All tickets escalate to this person at Level 2.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l2_escalations', to=settings.AUTH_USER_MODEL, verbose_name='Contact Center Director (Level 2)'),
        ),
        migrations.AlterField(
            model_name='escalationconfig',
            name='level1_minutes',
            field=models.IntegerField(default=2880, help_text='Minutes since ticket created before Level 1 escalation. Default 2880 = 48hrs.', verbose_name='Level 1 threshold (minutes)'),
        ),
        migrations.AlterField(
            model_name='escalationconfig',
            name='level2_minutes',
            field=models.IntegerField(default=1440, help_text='Minutes after Level 1 before Level 2 escalation. Default 1440 = 24hrs.', verbose_name='Level 2 threshold (minutes)'),
        ),
        migrations.AlterField(
            model_name='escalationrule',
            name='target_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Role'),
        ),
        migrations.AlterField(
            model_name='escalationrule',
            name='threshold_hours',
            field=models.IntegerField(default=48, verbose_name='Threshold (hours)'),
        ),
    ]
