# Generated by Django 4.2.7 on 2026-04-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_userprofile_level1_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='interaction_id',
            field=models.CharField(blank=True, help_text='XCALLY Interaction ID', max_length=100, null=True),
        ),
    ]
