# Generated by Django 4.2.7 on 2026-04-06 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_ticket_interaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Ticket Created'), ('ASSIGNED', 'Assigned to Department'), ('REASSIGNED', 'Reassigned to Another Department'), ('STATUS_CHANGED', 'Status Changed'), ('WAITING_FOR', 'Waiting for Input'), ('FOLLOWUP_ADDED', 'Followup Added'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Ticket Closed'), ('REOPENED', 'Ticket Reopened'), ('ATTACHMENT_ADDED', 'Attachment Added')], max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_activities', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.ticket')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Activity',
                'verbose_name_plural': 'Ticket Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
