# Generated by Django 4.2.7 on 2026-04-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ticket_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Category'),
        ),
    ]
