# Generated by Django 4.2.7 on 2026-04-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tickets', to='main.category', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_tickets', to='main.category', verbose_name='Main Category'),
        ),
    ]
