# Generated by Django 4.2.7 on 2026-04-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_generatedreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EscalationRule',
        ),
    ]
