# Generated by Django 4.2.7 on 2026-06-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_escalationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Email'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=255, null=True, verbose_name='Customer Gender (M/F)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer Phone Number'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='other_customer_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Customer Contact'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='queue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Queue'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='usd_customer_account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='USD Customer Account Number'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='zwg_customer_account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ZWG Customer Account Number'),
        ),
    ]
